[project]
name = "app-usuarios"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "pytest>=9.0.2",
    "rich>=14.3.2",
    "ruff>=0.15.1",
    "typer>=0.23.2",
]
